_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 80
                - 105
            "2":
                - 1
                - 41
                - 49
                - 55
                - 80
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.0
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
activation:
    value: relu
anneal_strategy:
    value: linear
batch_size:
    value: 16
clip_type:
    value: ViT-L/14@336px
dropout:
    value: 0.5
epochs:
    value: 100
hid_dim:
    value: 512
max_lr:
    value: 3e-05
pct_start:
    value: 0.2
weight_decay:
    value: 0.0002
